services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  backend:
    build:
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery_worker:
    build:
      dockerfile: Dockerfile
    depends_on:
      - backend
      - redis
      - postgres
    env_file: .env
    volumes:
      - .:/app
    command: >
      celery -A app.celery_worker.celery_app worker --loglevel=info

  celery_beat:
    build:
      dockerfile: Dockerfile
    depends_on:
      - backend
      - redis
      - postgres
    env_file: .env
    volumes:
      - .:/app
    command: >
      celery -A app.celery_worker.celery_app beat --loglevel=info

volumes:
  postgres_data:
  pgadmin_data: